"""
Knowledge Base Exporter

Advanced export capabilities with custom formats and templates.
"""

import json
import pandas as pd
from datetime import datetime
from typing import Dict, List, Optional, Any
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class KnowledgeBaseExporter:
    """Export knowledge base in various formats"""

    SUPPORTED_FORMATS = ['xlsx', 'csv', 'json', 'html', 'markdown', 'pdf']

    def __init__(self, output_dir: str = 'exports'):
        """
        Initialize exporter

        Args:
            output_dir: Base directory for exports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_to_excel(self, df: pd.DataFrame, output_file: str,
                       include_metadata: bool = True) -> str:
        """
        Export to Excel with formatting

        Args:
            df: DataFrame to export
            output_file: Output file path
            include_metadata: Include metadata sheet

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file

        with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
            # Main data sheet
            df.to_excel(writer, sheet_name='Knowledge Base', index=False)

            # Metadata sheet
            if include_metadata:
                metadata = pd.DataFrame([{
                    'Export Date': datetime.now().isoformat(),
                    'Total Entries': len(df),
                    'Version': '1.0'
                }])
                metadata.to_excel(writer, sheet_name='Metadata', index=False)

        logger.info(f"Exported to Excel: {output_path}")
        return str(output_path)

    def export_to_csv(self, df: pd.DataFrame, output_file: str) -> str:
        """
        Export to CSV

        Args:
            df: DataFrame to export
            output_file: Output file path

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file
        df.to_csv(output_path, index=False)

        logger.info(f"Exported to CSV: {output_path}")
        return str(output_path)

    def export_to_json(self, df: pd.DataFrame, output_file: str,
                      format_style: str = 'records') -> str:
        """
        Export to JSON

        Args:
            df: DataFrame to export
            output_file: Output file path
            format_style: JSON format (records, split, index, columns)

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file
        df.to_json(output_path, orient=format_style, indent=2, date_format='iso')

        logger.info(f"Exported to JSON: {output_path}")
        return str(output_path)

    def export_to_html(self, df: pd.DataFrame, output_file: str,
                      title: str = 'Knowledge Base Export') -> str:
        """
        Export to HTML with styling

        Args:
            df: DataFrame to export
            output_file: Output file path
            title: HTML title

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file

        html_template = f"""
<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }}
        h1 {{
            color: #333;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            background-color: white;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        th {{
            background-color: #FF9500;
            color: white;
            padding: 12px;
            text-align: left;
        }}
        td {{
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }}
        tr:hover {{
            background-color: #f9f9f9;
        }}
        .severity-critical {{
            color: #d32f2f;
            font-weight: bold;
        }}
        .severity-high {{
            color: #f57c00;
            font-weight: bold;
        }}
        .severity-medium {{
            color: #fbc02d;
        }}
        .severity-low {{
            color: #388e3c;
        }}
        .footer {{
            margin-top: 20px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p>Exported on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    <p>Total entries: {len(df)}</p>
    {df.to_html(index=False, classes='table', escape=False)}
    <div class="footer">
        <p>Generated by Sponge RCA Tool</p>
    </div>
</body>
</html>
"""

        with open(output_path, 'w') as f:
            f.write(html_template)

        logger.info(f"Exported to HTML: {output_path}")
        return str(output_path)

    def export_to_markdown(self, df: pd.DataFrame, output_file: str) -> str:
        """
        Export to Markdown

        Args:
            df: DataFrame to export
            output_file: Output file path

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file

        markdown = f"# Knowledge Base Export\n\n"
        markdown += f"**Export Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        markdown += f"**Total Entries:** {len(df)}\n\n"
        markdown += "---\n\n"

        # Convert DataFrame to markdown table
        markdown += df.to_markdown(index=False)

        with open(output_path, 'w') as f:
            f.write(markdown)

        logger.info(f"Exported to Markdown: {output_path}")
        return str(output_path)

    def export_summary_report(self, df: pd.DataFrame, output_file: str,
                             stats: Optional[Dict[str, Any]] = None) -> str:
        """
        Export summary report with statistics

        Args:
            df: DataFrame to export
            output_file: Output file path
            stats: Optional statistics dictionary

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file

        report = f"# Knowledge Base Summary Report\n\n"
        report += f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

        if stats:
            report += "## Statistics\n\n"

            if 'total_entries' in stats:
                report += f"- **Total Entries:** {stats['total_entries']}\n"

            if 'by_category' in stats:
                report += "\n### By Category\n"
                for category, count in stats['by_category'].items():
                    report += f"- {category}: {count}\n"

            if 'by_severity' in stats:
                report += "\n### By Severity\n"
                for severity, count in stats['by_severity'].items():
                    report += f"- {severity}: {count}\n"

            if 'with_solutions' in stats:
                report += f"\n- **Entries with Solutions:** {stats['with_solutions']}\n"

            if 'avg_confidence' in stats:
                report += f"- **Average Confidence:** {stats['avg_confidence']:.2f}\n"

        report += "\n## Top Issues\n\n"
        if 'Frequency' in df.columns:
            top_issues = df.nlargest(10, 'Frequency')
            for idx, row in top_issues.iterrows():
                report += f"### {row.get('Error_Pattern', 'Unknown')}\n"
                report += f"- **Category:** {row.get('Category', 'N/A')}\n"
                report += f"- **Severity:** {row.get('Severity', 'N/A')}\n"
                report += f"- **Frequency:** {row.get('Frequency', 0)}\n"
                report += f"- **Solution:** {row.get('Solution', 'No solution available')}\n\n"

        with open(output_path, 'w') as f:
            f.write(report)

        logger.info(f"Exported summary report: {output_path}")
        return str(output_path)

    def export_with_filters(self, df: pd.DataFrame,
                           filter_config: Dict[str, Any],
                           output_file: str,
                           format_type: str = 'xlsx') -> str:
        """
        Export with applied filters

        Args:
            df: DataFrame to export
            filter_config: Filter configuration
            output_file: Output file path
            format_type: Export format

        Returns:
            Path to exported file
        """
        from .filters import KnowledgeBaseFilter

        # Apply filters
        kb_filter = KnowledgeBaseFilter()
        filtered_df = kb_filter.apply_filters(df, filter_config)

        logger.info(f"Filtered from {len(df)} to {len(filtered_df)} entries")

        # Export based on format
        if format_type == 'xlsx':
            return self.export_to_excel(filtered_df, output_file)
        elif format_type == 'csv':
            return self.export_to_csv(filtered_df, output_file)
        elif format_type == 'json':
            return self.export_to_json(filtered_df, output_file)
        elif format_type == 'html':
            return self.export_to_html(filtered_df, output_file)
        elif format_type == 'markdown':
            return self.export_to_markdown(filtered_df, output_file)
        else:
            raise ValueError(f"Unsupported format: {format_type}")

    def export_by_category(self, df: pd.DataFrame,
                          output_dir: Optional[str] = None) -> Dict[str, str]:
        """
        Export separate files for each category

        Args:
            df: DataFrame to export
            output_dir: Optional output directory

        Returns:
            Dictionary mapping categories to file paths
        """
        if output_dir:
            export_dir = Path(output_dir)
        else:
            export_dir = self.output_dir / 'by_category'

        export_dir.mkdir(parents=True, exist_ok=True)

        exported_files = {}

        if 'Category' not in df.columns:
            logger.warning("No Category column found")
            return exported_files

        for category in df['Category'].unique():
            if pd.isna(category):
                continue

            category_df = df[df['Category'] == category]
            filename = f"{category.lower().replace(' ', '_')}.xlsx"
            output_path = export_dir / filename

            category_df.to_excel(output_path, index=False)
            exported_files[category] = str(output_path)

            logger.info(f"Exported {category}: {len(category_df)} entries")

        return exported_files

    def export_automation_ready(self, df: pd.DataFrame, output_file: str) -> str:
        """
        Export in format ready for automation scripts

        Args:
            df: DataFrame to export
            output_file: Output file path

        Returns:
            Path to exported file
        """
        output_path = self.output_dir / output_file

        # Create automation-friendly structure
        automation_data = []

        for _, row in df.iterrows():
            entry = {
                'id': str(hash(row.get('Error_Pattern', ''))),
                'pattern': row.get('Error_Pattern', ''),
                'category': row.get('Category', ''),
                'severity': row.get('Severity', ''),
                'issue_type': row.get('Issue_Type', ''),
                'solution': row.get('Solution', ''),
                'implementation_steps': row.get('Implementation_Steps', ''),
                'automation_applicable': bool(row.get('Implementation_Steps'))
            }
            automation_data.append(entry)

        with open(output_path, 'w') as f:
            json.dump(automation_data, f, indent=2)

        logger.info(f"Exported automation-ready data: {output_path}")
        return str(output_path)
